import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,FileText,Sparkles,Download,Target,ShieldCheck,BrainCircuit,RefreshCw,Plus,Trash2,Briefcase,GraduationCap,Code2,Award,Mail,Phone,MapPin,ExternalLink,ChevronRight,CheckCircle2,AlertTriangle,LayoutTemplate,MessageSquare,Play,ArrowRight,BarChart3,Lightbulb,Lock,Star,Copy,Clock,Send,RotateCcw} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const demoResume=`Aarav Sharma\nSoftware Engineer\naarav.sharma@email.com | +91 9876543210 | Hyderabad, India\nLinkedIn: linkedin.com/in/aaravsharma | GitHub: github.com/aaravsharma\n\nSUMMARY\nSoftware engineer building backend and AI-powered web applications.\n\nSKILLS\nPython, FastAPI, JavaScript, React, SQL, PostgreSQL, AWS, Git, REST APIs, Docker\n\nEXPERIENCE\nSoftware Engineering Intern — TechNova\nJun 2025 - Aug 2025\nBuilt REST APIs using Python and FastAPI. Worked with PostgreSQL and AWS services. Collaborated with a team using Git and agile development.\n\nPROJECTS\nWeather Intelligence Platform\nBuilt a FastAPI weather application with REST API integration and AI-powered recommendations.\n\nEDUCATION\nB.Tech Computer Science and Engineering — 2024-2028\n\nCERTIFICATIONS\nAWS Cloud Practitioner Essentials`;
const demoJD=`Backend Software Engineer\n\nWe are looking for a Backend Software Engineer to design, develop, and maintain scalable backend services and REST APIs.\n\nRequired Qualifications\n- Strong proficiency in Python.\n- Experience with FastAPI or similar Python web frameworks.\n- Strong understanding of REST API development.\n- Experience with SQL and PostgreSQL.\n- Hands-on experience with AWS.\n- Experience with Docker and containerized applications.\n- Familiarity with Kubernetes.\n- Understanding of CI/CD pipelines.\n- Proficiency with Git and collaborative software development.\n- Strong problem-solving and communication skills.\n- Bachelor's degree in Computer Science.\n\nPreferred\n- Microservices architecture\n- Redis or Kafka\n- Automated testing\n- Observability and application monitoring\n- AI-powered applications`;
const templates=[
 {id:'minimal',name:'Minimal ATS',tag:'Safest',desc:'Clean single-column layout designed for parsing.'},
 {id:'modern',name:'Modern Blue',tag:'Modern',desc:'Contemporary hierarchy with subtle color accents.'},
 {id:'executive',name:'Executive',tag:'Premium',desc:'Strong typography for experienced candidates.'},
 {id:'tech',name:'Tech Slate',tag:'Tech',desc:'Technical resume style with compact sections.'}
];

function Score({label,value,sub}){return <div className="score-card"><div className="score-ring"><span>{value}</span></div><div><div className="muted">{label}</div><strong>{sub}</strong></div></div>}
function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}

function App(){
 const [tab,setTab]=useState('analyzer'); const [resume,setResume]=useState(''); const [jd,setJd]=useState(''); const [file,setFile]=useState(null); const [analysis,setAnalysis]=useState(null); const [optimized,setOptimized]=useState(null); const [selected,setSelected]=useState([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const [builder,setBuilder]=useState({name:'',title:'',email:'',phone:'',location:'',linkedin:'',github:'',summary:'',skills:'',education:'',experience:'',projects:'',certifications:''});
 const [template,setTemplate]=useState('minimal'); const [interview,setInterview]=useState(null); const [answers,setAnswers]=useState([]); const [currentQ,setCurrentQ]=useState(0); const [answer,setAnswer]=useState(''); const [evalLoading,setEvalLoading]=useState(false); const [scores,setScores]=useState([]); const [interviewDone,setInterviewDone]=useState(false);
 const currentResume=optimized?.text||resume;
 const loadDemo=()=>{setResume(demoResume);setJd(demoJD);setAnalysis(null);setOptimized(null);setSelected([]);setError('');setTab('analyzer')};
 const analyzeNow=async()=>{if(!resume.trim()||!jd.trim())return setError('Add your resume and target job description first.');setLoading(true);setError('');try{const r=await fetch(`${API}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume_text:resume,job_description:jd})});if(!r.ok)throw Error(await r.text());setAnalysis(await r.json());setOptimized(null)}catch(e){setError('Backend is not reachable. Start FastAPI and check VITE_API_URL.')}finally{setLoading(false)}};
 const toggleRec=id=>setSelected(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id]);
 const optimize=async()=>{if(!analysis)return;const recs=analysis.recommendations.filter(x=>selected.includes(x.id)).map(x=>x.title+' — '+x.detail);setLoading(true);try{const r=await fetch(`${API}/api/optimize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume_text:resume,job_description:jd,selected_recommendations:recs})});if(!r.ok)throw Error();setOptimized(await r.json())}catch(e){setError('Optimization failed. Check the backend and Gemini configuration.')}finally{setLoading(false)}};
 const downloadTemplate=async(t)=>{try{const r=await fetch(`${API}/api/resume/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume_text:currentResume,template:t,filename:'RoleSync_Resume'})});if(!r.ok)throw Error();const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`RoleSync_${t}.docx`;a.click();URL.revokeObjectURL(a.href)}catch(e){setError('Could not generate DOCX. Make sure the backend is running.')}};
 const handleFile=async e=>{const f=e.target.files?.[0];if(!f)return;setFile(f);setLoading(true);try{if(f.type==='text/plain'){setResume(await f.text())}else{const fd=new FormData();fd.append('file',f);const r=await fetch(`${API}/api/resume/parse`,{method:'POST',body:fd});if(!r.ok)throw Error();const d=await r.json();setResume(d.text||'')}}catch(e){setError('Could not parse this file. PDF and DOCX parsing requires the backend.')}finally{setLoading(false)}};
 const buildText=()=>{const b=builder;return `${b.name||'Candidate'}\n${b.title}\n${b.email} | ${b.phone} | ${b.location}\n${b.linkedin?'LinkedIn: '+b.linkedin:''} ${b.github?'| GitHub: '+b.github:''}\n\nSUMMARY\n${b.summary}\n\nSKILLS\n${b.skills}\n\nEXPERIENCE\n${b.experience}\n\nPROJECTS\n${b.projects}\n\nEDUCATION\n${b.education}\n\nCERTIFICATIONS\n${b.certifications}`.replace(/\n{3,}/g,'\n\n')};
 const useBuilder=()=>{const t=buildText();setResume(t);setTab('analyzer');setAnalysis(null)};
 const startInterview=async()=>{if(!resume||!jd)return setError('Analyze a resume and job description first.');setLoading(true);setInterviewDone(false);setScores([]);setAnswers([]);setCurrentQ(0);try{const r=await fetch(`${API}/api/interview/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume_text:currentResume,job_description:jd})});if(!r.ok)throw Error();setInterview(await r.json());setTab('interview')}catch(e){setError('Could not start interview. Check the backend.')}finally{setLoading(false)}};
 const submitAnswer=async()=>{if(!interview||!answer.trim())return;setEvalLoading(true);const q=interview.questions[currentQ];try{const r=await fetch(`${API}/api/interview/evaluate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q.question,answer,resume_text:currentResume,job_description:jd,round_name:q.round})});const d=await r.json();setScores(s=>[...s,d]);setAnswers(a=>[...a,{question:q.question,answer,...d}]);setAnswer('');if(currentQ+1>=interview.questions.length)setInterviewDone(true);else setCurrentQ(x=>x+1)}catch(e){setError('Could not evaluate answer.')}finally{setEvalLoading(false)}};
 const interviewTotal=scores.length?Math.round(scores.reduce((a,x)=>a+x.score,0)/scores.length):0;
 return <div className="app">
  <header className="topbar"><div className="brand"><div className="logo"><Sparkles size={19}/></div><div><b>Role<span>Sync</span></b><small>AI Career Intelligence</small></div></div><nav><button className={tab==='analyzer'?'active':''} onClick={()=>setTab('analyzer')}>Analyzer</button><button className={tab==='builder'?'active':''} onClick={()=>setTab('builder')}><LayoutTemplate size={15}/> Builder</button><button className={tab==='interview'?'active':''} onClick={()=>setTab('interview')}><MessageSquare size={15}/> Mock Interview</button><button onClick={loadDemo}>Load Demo</button></nav><div className="trust"><ShieldCheck size={14}/> ATS-aware</div></header>
  {error&&<div className="errorbar"><AlertTriangle size={15}/>{error}<button onClick={()=>setError('')}>×</button></div>}
  {tab==='analyzer'&&<>
   <section className="hero"><div><Badge tone="purple">AI-POWERED CAREER COPILOT</Badge><h1>Make your resume <span>match the role.</span><br/>Then practice the interview.</h1><p>Semantic job matching, ATS diagnostics, AI recommendations, multi-template resumes and a role-specific mock interview — in one workspace.</p><div className="hero-actions"><button className="primary" onClick={loadDemo}><Play size={16}/> Try live demo</button><button className="ghost" onClick={()=>document.getElementById('workspace').scrollIntoView({behavior:'smooth'})}>Start with my resume <ArrowRight size={16}/></button></div></div><div className="hero-visual"><div className="floating-card"><div className="tiny">ROLE MATCH</div><strong>84%</strong><div className="bar"><i style={{width:'84%'}}/></div><small>Skills + semantic context</small></div><div className="floating-card right"><div className="tiny">ATS SCORE</div><strong>91<span>/100</span></strong><div className="mini-tags"><Badge>Keywords</Badge><Badge>Format</Badge><Badge>Structure</Badge></div></div><div className="hero-orb"><BrainCircuit size={56}/></div></div></section>
   <section id="workspace" className="workspace"><div className="section-title"><div><Badge>01 · ANALYZE</Badge><h2>Resume ↔ Job Match</h2><p>Upload a PDF/DOCX or paste text, then compare it against the target role.</p></div><button className="secondary" onClick={loadDemo}><RefreshCw size={15}/> Load demo data</button></div>
    <div className="input-grid"><div className="panel"><div className="panel-head"><div><FileText size={18}/><b>Your Resume</b></div><label className="upload"><Upload size={15}/> {file?file.name:'Upload PDF / DOCX'}<input type="file" accept=".pdf,.docx,.txt" onChange={handleFile}/></label></div><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here..."/></div><div className="panel"><div className="panel-head"><div><Target size={18}/><b>Target Job Description</b></div><span className="muted">Required for matching</span></div><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the job description here..."/></div></div>
    <button className="analyze-btn" onClick={analyzeNow} disabled={loading}>{loading?<RefreshCw className="spin" size={18}/>:<Sparkles size={18}/>} {loading?'Analyzing with AI...':'Analyze my match'}<ChevronRight size={18}/></button>
   </section>
   {analysis&&<section className="results"><div className="section-title"><div><Badge tone="green">02 · RESULTS</Badge><h2>Your role-fit report</h2><p>Use the gaps and recommendations to improve the resume without inventing experience.</p></div><div className="result-actions"><button className="secondary" onClick={startInterview}><MessageSquare size={15}/> Practice interview</button></div></div>
    <div className="scores"><Score label="Role Match" value={analysis.match_score+'%'} sub="Overall alignment"/><Score label="ATS Score" value={analysis.ats_score} sub="Out of 100"/><Score label="Semantic Match" value={analysis.semantic_similarity+'%'} sub="Context similarity"/><Score label="Keywords" value={analysis.keyword_coverage+'%'} sub="JD coverage"/></div>
    <div className="result-grid"><div className="panel"><div className="panel-head"><b><CheckCircle2 size={17}/> Matched skills</b><span>{analysis.matched_skills.length} found</span></div><div className="chips">{analysis.matched_skills.map(x=><Badge key={x} tone="green">{x}</Badge>)}</div>{!analysis.matched_skills.length&&<p className="muted">No known skills matched yet.</p>}</div><div className="panel"><div className="panel-head"><b><AlertTriangle size={17}/> Skill gaps</b><span>{analysis.missing_skills.length} to review</span></div><div className="chips">{analysis.missing_skills.map(x=><Badge key={x} tone="red">{x}</Badge>)}</div><p className="micro">Only add a missing skill if you actually have the experience.</p></div></div>
    <div className="result-grid"><div className="panel"><div className="panel-head"><b><ShieldCheck size={17}/> ATS breakdown</b></div>{Object.entries(analysis.ats_breakdown).map(([k,v])=><div className="break" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="panel"><div className="panel-head"><b><Lightbulb size={17}/> AI recommendations</b><span>Select what you want to apply</span></div>{analysis.recommendations.map(r=><label className={'rec '+(selected.includes(r.id)?'selected':'')} key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggleRec(r.id)}/><span><strong>{r.title}</strong><small>{r.detail}</small></span><CheckCircle2 size={17}/></label>)}<button className="optimize-btn" onClick={optimize} disabled={loading}>{loading?<RefreshCw className="spin" size={16}/>:<Sparkles size={16}/>} {selected.length ? `Optimize with ${selected.length} selected recommendation${selected.length===1?'':'s'}` : 'Optimize with recommended improvements'}</button></div></div>
   </section>}
   {optimized&&<section className="optimized"><div className="section-title"><div><Badge tone="purple">03 · OPTIMIZED</Badge><h2>Before → After</h2><p>Review the generated version, then choose a resume template to export.</p></div><Badge tone="green">AI optimization complete</Badge></div><div className="before-after"><div className="metric"><span>Before</span><strong>{analysis.ats_score}/100</strong></div><ArrowRight/><div className="metric"><span>After</span><strong>{optimized.analysis.ats_score}/100</strong></div><div className="metric"><span>Role match</span><strong>{optimized.analysis.match_score}%</strong></div></div><div className="optimized-text">{optimized.text}</div><div className="template-grid">{templates.map(t=><div className={'template-card '+(template===t.id?'chosen':'')} key={t.id} onClick={()=>setTemplate(t.id)}><div className={'template-preview '+t.id}><div/><div/><div/><div/><div/></div><div className="template-copy"><div><strong>{t.name}</strong><Badge>{t.tag}</Badge></div><small>{t.desc}</small><button className="download" onClick={()=>downloadTemplate(t.id)}><Download size={15}/> Download DOCX</button></div></div>)}</div></section>}
  </>}
  {tab==='builder'&&<Builder builder={builder} setBuilder={setBuilder} template={template} setTemplate={setTemplate} useBuilder={useBuilder} download={()=>{const t=buildText();setResume(t);setTimeout(()=>downloadTemplate(template),0)}}/>
  }
  {tab==='interview'&&<Interview interview={interview} loading={loading} startInterview={startInterview} currentQ={currentQ} answer={answer} setAnswer={setAnswer} submitAnswer={submitAnswer} evalLoading={evalLoading} scores={scores} interviewDone={interviewDone} total={interviewTotal} answers={answers} resume={resume} jd={jd}/>} 
  <footer><div><b>RoleSync AI</b><small>Resume intelligence · ATS · Optimization · Interview practice</small></div><span>Built for hackathon demo · Keep every claim truthful</span></footer>
 </div>
}

function Builder({builder,setBuilder,template,setTemplate,useBuilder,download}){const fields=[['name','Full name',true],['title','Target title',false],['email','Email',false],['phone','Phone',false],['location','Location',false],['linkedin','LinkedIn',false],['github','GitHub',false],['summary','Professional summary',true],['skills','Skills (comma separated)',true],['education','Education',true],['experience','Experience',true],['projects','Projects',true],['certifications','Certifications',true]];return <section className="builder"><div className="section-title"><div><Badge tone="purple">RESUME BUILDER</Badge><h2>Build once. Export four ways.</h2><p>Fill the structured builder, preview the ATS-safe layout and download any template.</p></div><button className="primary" onClick={useBuilder}><CheckCircle2 size={16}/> Use in Analyzer</button></div><div className="builder-grid"><div className="panel builder-form">{fields.map(([k,label,wide])=><label className={wide?'wide':''} key={k}><span>{label}</span>{wide?<textarea value={builder[k]} onChange={e=>setBuilder({...builder,[k]:e.target.value})}/>:<input value={builder[k]} onChange={e=>setBuilder({...builder,[k]:e.target.value})}/>}</label>)}</div><div className="builder-side"><div className="template-selector"><b><LayoutTemplate size={16}/> Choose template</b>{templates.map(t=><button className={template===t.id?'selected':''} onClick={()=>setTemplate(t.id)} key={t.id}><span>{t.name}</span><small>{t.tag}</small></button>)}</div><div className={'resume-paper '+template}><h2>{builder.name||'Your Name'}</h2><p>{builder.title||'Target Role'} · {builder.email||'email@example.com'} · {builder.location||'City, Country'}</p><hr/><section><h4>SUMMARY</h4><p>{builder.summary||'Your professional summary will appear here.'}</p></section><section><h4>SKILLS</h4><p>{builder.skills||'Python · SQL · AWS · Git'}</p></section><section><h4>EXPERIENCE</h4><p>{builder.experience||'Experience details and impact bullets.'}</p></section><section><h4>PROJECTS</h4><p>{builder.projects||'Relevant projects and outcomes.'}</p></section><section><h4>EDUCATION</h4><p>{builder.education||'Degree · University · Year'}</p></section></div><button className="analyze-btn full" onClick={download}><Download size={17}/> Download selected template</button></div></div></section>}

function Interview({interview,loading,startInterview,currentQ,answer,setAnswer,submitAnswer,evalLoading,scores,interviewDone,total,answers,resume,jd}){if(!interview)return <section className="interview-empty"><div className="empty-icon"><MessageSquare size={35}/></div><Badge tone="purple">MOCK INTERVIEW LAB</Badge><h1>Practice the interview you are actually applying for.</h1><p>Questions are generated from your resume and target job, across multiple rounds — including role-specific technical questions.</p><div className="rounds"><span>01 Introduction</span><span>02 Resume Deep Dive</span><span>03 Technical</span><span>04 Behavioral + System Design</span></div><button className="primary" onClick={startInterview} disabled={loading}>{loading?<RefreshCw className="spin"/>:<Play size={17}/>} Start interview</button>{!resume||!jd?<small className="muted">Analyze a resume + job description first.</small>:null}</section>;
 if(interviewDone)return <section className="interview"><div className="interview-score"><Badge tone="green">INTERVIEW COMPLETE</Badge><h1>{total}<span>/100</span></h1><p>Average performance across {scores.length} evaluated answers.</p><div className="round-score">{Object.entries(scores.reduce((a,x,i)=>{const r=interview.questions[i]?.round||'Round';(a[r]??=[]).push(x.score);return a},{})).map(([r,v])=><div key={r}><span>{r}</span><strong>{Math.round(v.reduce((a,b)=>a+b,0)/v.length)}/100</strong></div>)}</div><button className="secondary" onClick={startInterview}><RotateCcw size={15}/> Retake interview</button></div><div className="answer-review">{answers.map((a,i)=><div className="review" key={i}><Badge>{i+1}</Badge><div><strong>{a.question}</strong><p>Your answer: {a.answer}</p><small>Score {a.score}/100 · {a.feedback}</small><em>Improve: {a.improvement}</em></div></div>)}</div></section>;
 const q=interview.questions[currentQ];return <section className="interview"><div className="interview-head"><div><Badge tone="purple">MOCK INTERVIEW · {currentQ+1}/{interview.questions.length}</Badge><h2>{q.round}</h2><p>Difficulty: <strong>{q.difficulty}</strong> · Answer naturally, like a real interview.</p></div><div className="progress"><span style={{width:`${(currentQ/interview.questions.length)*100}%`}}/></div></div><div className="question-card"><div className="question-meta"><Badge>{q.round}</Badge><Badge tone={q.difficulty==='Hard'?'red':q.difficulty==='Medium'?'yellow':'green'}>{q.difficulty}</Badge></div><h1>{q.question}</h1><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer here... Include reasoning, examples, code/query when relevant." autoFocus/><div className="question-footer"><small>{answer.length} characters · Be specific and explain your reasoning</small><button className="primary" onClick={submitAnswer} disabled={evalLoading||!answer.trim()}>{evalLoading?<RefreshCw className="spin" size={16}/>:<Send size={16}/>} Submit answer</button></div></div></section>}

createRoot(document.getElementById('root')).render(<App/>);
